name: Deploy to GitHub Pages
on:
  push:
    branches: [ "feat/screen2.4" ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3   # <-- correct action for Pages
        with:
          path: .                                # publish the repo root
      - uses: actions/deploy-pages@v4
